# Generated by Django 4.2.16 on 2024-10-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='imdb_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='tmdb_id',
            field=models.FloatField(blank=True),
        ),
    ]
