# Generated by Django 4.2.16 on 2024-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_links_imdb_id_alter_links_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
