# Generated by Django 4.2.16 on 2024-10-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_movie_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['movie_id'], 'verbose_name_plural': 'Movies'},
        ),
    ]
